#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

#include <SynthDefs.h>
#include <SynthString.h>
#include <WaveTable.h>
#include <GenWave.h>
#include <GenWaveWT.h>
#include <GenWaveX.h>
#include <GenNoise.h>
#include <EnvGen.h>
#include <EnvGenSeg.h>
#include <BiQuad.h>
#include <AllPass.h>
#include <Filter.h>
#include <DynFilter.h>
#include <DelayLine.h>
#include <Flanger.h>
#include <Reverb.h>
//#include <Mixer.h>
//#include <WaveFile.h>
//#include <SynthList.h>
//#include <XmlWrap.h>
//#include <SeqEvent.h>
//#include <Instrument.h>
//#include <Sequencer.h>

#include <NLConvert.h>
#include <SequenceFile.h>

#include <Tone.h>
#include <LFO.h>
#include <SubSynth.h>
#include <AddSynth.h>
#include <FMSynth.h>
#include <MatrixSynth.h>
#include <WFSynth.h>
#include <LoadInstrLib.h>
