/////////////////////////////////////////////////////////////////////////
// BasicSynth - Example 5 (Chapter 10)
//
// Various Filters
//
// Bi-Quad Filters (LP,HP,BP) and allpass applied to noise and a sawtooth wave.
// FIR and IIR averaging filters.
// FIR Convolution
//
// use: Example05 [duration [pitch [cutoff]]]
//
// Copyright 2008, Daniel R. Mitchell
/////////////////////////////////////////////////////////////////////////
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "SynthDefs.h"
#include "WaveFile.h"
#include "EnvGen.h"
#include "EnvGenSeg.h"
#include "GenWaveWT.h"
#include "GenNoise.h"
#include "BiQuad.h"
#include "AllPass.h"
#include "Filter.h"
#include "DynFilter.h"

WaveFile wvf;

void Generate(FrqValue duration, GenUnit *wv, EnvGen *eg, GenUnit *fp)
{
	long totalSamples = (long) (duration * synthParams.sampleRate);
	AmpValue sig, flt;

	eg->Reset();

	for (long n = 0; n < totalSamples; n++)
	{
		sig = eg->Gen() * wv->Sample(0);
		flt = fp->Sample(sig);
		wvf.Output1(flt);
		//wvf.Output2(sig, flt); //<- good for comparing filter output with original signal
	}
}

void Silence(FrqValue duration)
{
	long totalSamples = (long) ((duration * synthParams.sampleRate) + 0.5);
	for (long n = 0; n < totalSamples; n++)
		wvf.Output1(0);
}


int main(int argc, char *argv[])
{
	int pitch = 60;
	FrqValue duration = 1.0;
	FrqValue cutoff = 1000.0;

	if (argc > 1)
		duration = atof(argv[1]);
	if (argc > 2)
		pitch = atoi(argv[2]);
	if (argc > 3)
		cutoff = atof(argv[3]);

	InitSynthesizer();

	FrqValue frequency = synthParams.GetFrequency(pitch);

	if (wvf.OpenWaveFile("example05.wav", 2))
	{
		printf("Cannot open wavefile for output\n");
		exit(1);
	}

	EnvGen eg;
	eg.InitEG(0.707, duration, 0.1, 0.2);

	GenWaveNoise nz;
	FilterLP lpf;
	FilterHP hpf;
	FilterBP bpf;
	AllPassFilter apf;

	/////////////////////////////////////////////////
	// 1 - reference white noise
	/////////////////////////////////////////////////
	lpf.Init(0.0, 1.0);
	Generate(duration, &nz, &eg, &lpf);

	/////////////////////////////////////////////////
	// 2 - low pass filter
	/////////////////////////////////////////////////
	//lpf.Init(cutoff, 3.0);
	lpf.Init(cutoff, 1.0);
	Generate(duration, &nz, &eg, &lpf);

	/////////////////////////////////////////////////
	// 3 - high pass filter
	/////////////////////////////////////////////////
	hpf.Init(cutoff, 0.7);
	Generate(duration, &nz, &eg, &hpf);

	/////////////////////////////////////////////////
	// 4 - band pass filter
	/////////////////////////////////////////////////
	bpf.Init(cutoff, 1.0, 200.0);
	Generate(duration, &nz, &eg, &bpf);

	/////////////////////////////////////////////////
	// 5 - allpass filter
	/////////////////////////////////////////////////
	apf.InitAP(0.5);
	Generate(duration, &nz, &eg, &apf);

	Silence(0.5);

	GenWaveI wv;
	wv.InitWT(frequency, WT_SQR);

	cutoff = 3*frequency;
	/////////////////////////////////////////////////
	// 6 - reference wave
	/////////////////////////////////////////////////
	lpf.Init(0.0, 1.0);
	Generate(duration, &wv, &eg, &lpf);

	/////////////////////////////////////////////////
	// 7 - low pass filter
	/////////////////////////////////////////////////
	lpf.Init(cutoff, 1.0);
	Generate(duration, &wv, &eg, &lpf);

	/////////////////////////////////////////////////
	// 8 - high pass filter
	/////////////////////////////////////////////////
	hpf.Init(cutoff, 1.0);
	Generate(duration, &wv, &eg, &hpf);

	/////////////////////////////////////////////////
	// 9,10 - band pass filters
	/////////////////////////////////////////////////
	bpf.Init(cutoff, 1.0, 200.0);
	Generate(duration, &wv, &eg, &bpf);
	bpf.Init(cutoff, 1.0, 500.0);
	Generate(duration, &wv, &eg, &bpf);

	/////////////////////////////////////////////////
	// 11,12 - resonator band pass filters
	/////////////////////////////////////////////////
	Reson resf;
	resf.InitRes(cutoff, 1.0, 0.9);
	Generate(duration, &wv, &eg, &resf);
	resf.InitRes(cutoff, 1.0, 0.7);
	Generate(duration, &wv, &eg, &resf);

	/////////////////////////////////////////////////
	// 10 - Allpass filter
	/////////////////////////////////////////////////
	apf.InitAP(0.5);
	Generate(duration, &wv, &eg, &apf);

	/////////////////////////////////////////////////
	// 11 - Running average filter
	/////////////////////////////////////////////////
	FilterAvgN avgn;
	avgn.InitFilter(4);
	Generate(duration, &wv, &eg, &avgn);

	Silence(0.5);

	/////////////////////////////////////////////////
	// 12 - FIR lowpass filter (convolution)
	/////////////////////////////////////////////////
	FilterFIRn firn;
	float h[32]; // FIR filter coeffcients 
	// fc = 1000hz, (-60db at 10khz) 
	// generated by Digital Filter Analyzer (http://www.digitalfilter.com)
	h[  0] =  0.027961015;
	h[  1] =  0.083693340;
	h[  2] =  0.155213352;
	h[  3] =  0.206230444;
	h[  4] =  0.206230444;
	h[  5] =  0.155213352;
	h[  6] =  0.083693340;
	h[  7] =  0.027961015;
	firn.Init(8, h);
	Generate(duration, &wv, &eg, &firn);

	h[  0] = -0.002747550;
	h[  1] = -0.008972243;
	h[  2] = -0.013909771;
	h[  3] = -0.004676988;
	h[  4] =  0.032612163;
	h[  5] =  0.099181436;
	h[  6] =  0.174930924;
	h[  7] =  0.225961565;
	h[  8] =  0.225961565;
	h[  9] =  0.174930924;
	h[ 10] =  0.099181436;
	h[ 11] =  0.032612163;
	h[ 12] = -0.004676988;
	h[ 13] = -0.013909771;
	h[ 14] = -0.008972243;
	h[ 15] = -0.002747550;
	firn.Init(16, h);
	Generate(duration, &wv, &eg, &firn);

	h[  0] =  0.000000406;
	h[  1] =  0.000039607;
	h[  2] =  0.000259015;
	h[  3] =  0.000893486;
	h[  4] =  0.001996369;
	h[  5] =  0.002887092;
	h[  6] =  0.001801127;
	h[  7] = -0.003386830;
	h[  8] = -0.012931337;
	h[  9] = -0.022509999;
	h[ 10] = -0.022554891;
	h[ 11] = -0.001852118;
	h[ 12] =  0.045174841;
	h[ 13] =  0.111774641;
	h[ 14] =  0.178305011;
	h[ 15] =  0.220106530;
	h[ 16] =  0.220106530;
	h[ 17] =  0.178305011;
	h[ 18] =  0.111774641;
	h[ 19] =  0.045174841;
	h[ 20] = -0.001852118;
	h[ 21] = -0.022554891;
	h[ 22] = -0.022509999;
	h[ 23] = -0.012931337;
	h[ 24] = -0.003386830;
	h[ 25] =  0.001801127;
	h[ 26] =  0.002887092;
	h[ 27] =  0.001996369;
	h[ 28] =  0.000893486;
	h[ 29] =  0.000259015;
	h[ 30] =  0.000039607;
	h[ 31] =  0.000000406;
	firn.Init(32, h);
	Generate(duration, &wv, &eg, &firn);

	// fc = 1000hz, (-60db at 5khz) 
	h[  0] =  0.048904450;
	h[  1] =  0.041711461;
	h[  2] =  0.051772913;
	h[  3] =  0.057376838;
	h[  4] =  0.057376838;
	h[  5] =  0.051772913;
	h[  6] =  0.041711461;
	h[  7] =  0.048904450;
	firn.Init(8, h);
	Generate(duration, &wv, &eg, &firn);

	h[  0] =  0.011450321;
	h[  1] =  0.020925663;
	h[  2] =  0.036206042;
	h[  3] =  0.054620473;
	h[  4] =  0.074191105;
	h[  5] =  0.092331533;
	h[  6] =  0.106342885;
	h[  7] =  0.113981762;
	h[  8] =  0.113981762;
	h[  9] =  0.106342885;
	h[ 10] =  0.092331533;
	h[ 11] =  0.074191105;
	h[ 12] =  0.054620473;
	h[ 13] =  0.036206042;
	h[ 14] =  0.020925663;
	h[ 15] =  0.011450321;
	firn.Init(16, h);
	Generate(duration, &wv, &eg, &firn);

	h[  0] = -0.001100185;
	h[  1] = -0.002450162;
	h[  2] = -0.004547048;
	h[  3] = -0.007005208;
	h[  4] = -0.009181706;
	h[  5] = -0.010099613;
	h[  6] = -0.008568940;
	h[  7] = -0.003421262;
	h[  8] =  0.006198307;
	h[  9] =  0.020534175;
	h[ 10] =  0.039007830;
	h[ 11] =  0.060163755;
	h[ 12] =  0.081801173;
	h[ 13] =  0.101297845;
	h[ 14] =  0.116063661;
	h[ 15] =  0.124023204;
	h[ 16] =  0.124023204;
	h[ 17] =  0.116063661;
	h[ 18] =  0.101297845;
	h[ 19] =  0.081801173;
	h[ 20] =  0.060163755;
	h[ 21] =  0.039007830;
	h[ 22] =  0.020534175;
	h[ 23] =  0.006198307;
	h[ 24] = -0.003421262;
	h[ 25] = -0.008568940;
	h[ 26] = -0.010099613;
	h[ 27] = -0.009181706;
	h[ 28] = -0.007005208;
	h[ 29] = -0.004547048;
	h[ 30] = -0.002450162;
	h[ 31] = -0.001100185;
	
	firn.Init(32, h);
	Generate(duration, &wv, &eg, &firn);

	/////////////////////////////////////////////////
	// 13 - Dynamic lowpass filter
	/////////////////////////////////////////////////
	DynFilterLP dynfilt;
	dynfilt.InitFilter(100.0, 0.2, 4000.0, 0.4, 1000.0, 0.2, 100.0);
	Generate(duration, &wv, &eg, &dynfilt);

	wvf.CloseWaveFile();
	return 0;
}
