//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mswin.rc
//
#define IDC_ERROR_CLEAR                 3
#define IDC_ERROR_REFRESH               4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_PRODUCT                     129
#define IDD_FINDREPL                    203
#define IDR_POPUP                       204
#define IDD_PROJECT_PROPERTIES          210
#define IDI_MVUP                        211
#define IDI_MVDN                        212
#define IDI_ADD                         213
#define IDI_REM                         214
#define IDD_FILE_PROPERTIES             215
#define IDR_MAINTB                      216
#define IDB_STOP                        262
#define IDB_WINDOW                      263
#define IDB_AUDIO                       264
#define IDB_CABINET                     265
#define IDB_CD                          266
#define IDB_COPY                        267
#define IDB_COPYFOLDER                  268
#define IDB_CUT                         269
#define IDB_DATABASE                    270
#define IDB_DOCUMENT                    271
#define IDB_REDOX                       272
#define IDB_UNDO                        273
#define IDB_EDITCODE                    274
#define IDB_FIND                        275
#define IDB_FINDNEXT                    276
#define IDB_FLAGBLUE                    277
#define IDB_FLAGGREEN                   278
#define IDB_FLAGRED                     279
#define IDB_GENERICFILE                 280
#define IDB_LIBRARY                     281
#define IDB_NEWDOCUMENT                 282
#define IDB_NEWFOLDER                   283
#define IDB_OPEN                        284
#define IDB_OPENFOLDER                  285
#define IDB_PASTE                       286
#define IDB_PAUSE                       287
#define IDB_PLAY                        288
#define IDB_AFILE                       289
#define IDB_PRINT                       290
#define IDB_PRINTPREVIEW                291
#define IDB_PRINTSETUP                  292
#define IDB_PROPERTIES                  293
#define IDB_LOCKFORM                    294
#define IDB_PUSHPIN                     295
#define IDB_REFRESH                     296
#define IDB_RENAME                      297
#define IDB_REPEAT                      298
#define IDB_SAVE                        299
#define IDB_SAVEALL                     300
#define IDB_SCRIPTFILE                  301
#define IDB_NOTELIST                    302
#define IDB_NEWNOTELIST                 303
#define IDB_NEWSEQUENCE                 304
#define IDB_SEQUENCE                    305
#define IDB_PLAY1                       306
#define IDD_GENERATE                    307
#define IDD_WVTABLE                     308
#define IDD_MIXER_SETUP                 309
#define IDI_INFO                        311
#define IDD_WT_SELECT                   311
#define IDD_GET_VALUE                   312
#define IDD_INSTR_PROPERTIES            313
#define IDD_KEYBOARD                    314
#define IDI_WHOLENOTE                   315
#define IDI_HALFNOTE                    316
#define IDI_QUARTNOTE                   317
#define IDI_EIGHTHNOTE                  318
#define IDI_SIXTEENTHNOTE               319
#define IDD_EFFECTS                     320
#define IDD_LIB_PROPERTIES              321
#define IDD_SELECT_INSTR                323
#define IDD_OPTIONS                     324
#define IDD_WVF_PROPERTIES              325
#define IDD_NAME_PROPERTIES             326
#define IDB_WHOLE24                     332
#define IDB_HALF24                      333
#define IDB_QUART24                     334
#define IDB_SIXTEENTH24                 335
#define IDB_EIGHTH24                    336
#define IDI_GENERATE                    337
#define IDI_SPEAKER                     338
#define IDI_AUDIOCD                     339
#define IDI_STOP                        343
#define IDI_START                       344
#define IDI_RECORD                      345
#define IDI_COPYNOTES                   346
#define IDI_NOTEGROUP                   347
#define IDD_SCORE_ERRORS                349
#define IDB_CCLIC                       350
#define IDD_MODSYNTH_CONFIG             351
#define IDD_MODSYNTH_CONNECT            352
#define IDC_FIND_TEXT                   1000
#define IDC_REPL_TEXT                   1001
#define IDC_MATCH_CASE                  1002
#define IDC_WHOLE_WORD                  1003
#define IDC_REGEXP                      1004
#define IDC_START_WORD                  1005
#define IDC_FIND_NEXT                   1006
#define IDC_REPLACE                     1007
#define IDC_REPLACE_ALL                 1008
#define IDC_STAT_TEXT                   1009
#define IDC_PROJECT_FILE                1010
#define IDC_REPLACE_SELALL              1010
#define IDC_PROJECT_NAME                1011
#define IDC_PROJECT_DESCR               1012
#define IDC_PROJECT_COMPOSER            1013
#define IDC_PROJECT_OUTPUT              1014
#define IDC_PROJECT_OUT_BROWSE          1015
#define IDC_PROJECT_WV_BROWSE           1016
#define IDC_PROJECT_SAMPLERATE          1022
#define IDC_PROJECT_WTSIZE              1023
#define IDC_PROJECT_WTUSER              1026
#define IDC_PROJECT_SAMPLEFMT           1027
#define IDC_PROJECT_COPYRIGHT           1028
#define IDC_PROJECT_PATH                1029
#define IDC_PROJECT_PATH_ADD            1033
#define IDC_PROJECT_PATH_REM            1034
#define IDC_PROJECT_PATH_UP             1035
#define IDC_FILE_NAME                   1035
#define IDC_PROJECT_PATH_DN             1036
#define IDC_PROJECT_IN_BROWSE           1037
#define IDC_FILE_INCLUDE                1039
#define IDC_FILE_BROWSE                 1040
#define IDC_START                       1041
#define IDC_TEXT                        1042
#define IDC_PLAY_ALL                    1043
#define IDC_PLAY_SOME                   1044
#define IDC_PLAY_FROM                   1045
#define IDC_PLAY_TO                     1046
#define IDC_TIME                        1047
#define IDC_STOP                        1048
#define IDC_WV_NAME                     1050
#define IDC_LEFT_PEAK                   1050
#define IDC_WV_DESCR                    1051
#define IDC_RIGHT_PEAK                  1051
#define IDC_WV_GIBBS                    1053
#define IDC_WV_P1                       1054
#define IDC_WV_P2                       1055
#define IDC_WV_P3                       1056
#define IDC_WV_P4                       1057
#define IDC_WV_P5                       1058
#define IDC_WV_P6                       1059
#define IDC_WV_P7                       1060
#define IDC_WV_P8                       1061
#define IDC_WV_P9                       1062
#define IDC_WV_P10                      1063
#define IDC_WV_P11                      1064
#define IDC_WV_P12                      1065
#define IDC_WV_P13                      1066
#define IDC_WV_P14                      1067
#define IDC_WV_P15                      1068
#define IDC_WV_P16                      1069
#define IDC_WV_E1                       1070
#define IDC_WV_E2                       1071
#define IDC_WV_E3                       1072
#define IDC_WV_E4                       1073
#define IDC_WV_E5                       1074
#define IDC_WV_E6                       1075
#define IDC_WV_E7                       1076
#define IDC_WV_E8                       1077
#define IDC_WV_E9                       1078
#define IDC_WV_E10                      1079
#define IDC_WV_E11                      1080
#define IDC_WV_E12                      1081
#define IDC_WV_E13                      1082
#define IDC_WV_E14                      1083
#define IDC_WV_E15                      1084
#define IDC_WV_E16                      1085
#define IDC_WV_PH1                      1086
#define IDC_WV_PH2                      1087
#define IDC_WV_PH3                      1088
#define IDC_WV_PH4                      1089
#define IDC_WV_PH5                      1090
#define IDC_WV_PH6                      1091
#define IDC_WV_PH7                      1092
#define IDC_WV_PH8                      1093
#define IDC_WV_PH9                      1094
#define IDC_WV_PH10                     1095
#define IDC_WV_PH11                     1096
#define IDC_WV_PH12                     1097
#define IDC_WV_PH13                     1098
#define IDC_WV_PH14                     1099
#define IDC_WV_PH15                     1100
#define IDC_WV_PH16                     1101
#define IDC_WV_GRAPH                    1102
#define IDC_WV_REF                      1103
#define IDC_WV_M1                       1104
#define IDC_WV_M2                       1105
#define IDC_PLAY_LIVE                   1105
#define IDC_WV_M3                       1106
#define IDC_INPUTS                      1106
#define IDC_WV_M4                       1107
#define IDC_WV_M5                       1108
#define IDC_FX_TYPE                     1108
#define IDC_WV_M6                       1109
#define IDC_FX_LIST                     1109
#define IDC_WV_M7                       1110
#define IDC_PAN_LIN                     1110
#define IDC_WV_M8                       1111
#define IDC_PAN_TRIG                    1111
#define IDC_WV_M9                       1112
#define IDC_PAN_SQRT                    1112
#define IDC_WV_M10                      1113
#define IDC_FX_ADD                      1113
#define IDC_WV_M11                      1114
#define IDC_FX_REM                      1114
#define IDC_WV_M12                      1115
#define IDC_FX_UP                       1115
#define IDC_WV_M13                      1116
#define IDC_FX_DN                       1116
#define IDC_WV_M14                      1117
#define IDC_FX_EDIT                     1117
#define IDC_WV_M15                      1118
#define IDC_WT_LIST                     1118
#define IDC_WV_M16                      1119
#define IDC_WT_GRAPH                    1119
#define IDC_WV_CLR                      1120
#define IDC_VALUE                       1120
#define IDC_WV_SQR                      1121
#define IDC_PROMPT                      1121
#define IDC_WV_SAW                      1122
#define IDC_INST_TYPE                   1122
#define IDC_WV_SIN                      1124
#define IDC_WV_PLS                      1125
#define IDC_INST_NUM                    1125
#define IDC_INSTRUMENT                  1126
#define IDC_VOLUME                      1128
#define IDC_NOTE_W                      1130
#define IDC_NOTE_H                      1131
#define IDC_NOTE_Q                      1132
#define IDC_NOTE_E                      1133
#define IDC_NOTE_S                      1134
#define IDC_CHANNEL                     1136
#define IDC_RECORD                      1137
#define IDC_COPYNOTES                   1138
#define IDC_PROJECT_LEAD                1139
#define IDC_GROUP                       1139
#define IDC_PROJECT_TAIL                1140
#define IDC_FX_NAME                     1142
#define IDC_VAL1                        1143
#define IDC_VAL2                        1144
#define IDC_VAL3                        1145
#define IDC_VAL4                        1146
#define IDC_VAL5                        1147
#define IDC_EDIT1                       1148
#define IDC_EDIT2                       1149
#define IDC_EDIT3                       1150
#define IDC_EDIT4                       1151
#define IDC_EDIT5                       1152
#define IDC_RESET                       1153
#define IDC_PAN_LBL                     1154
#define IDC_PAN                         1155
#define IDC_VOL_LBL                     1156
#define IDC_VOL                         1157
#define IDC_PROJECT_WVPATH              1158
#define IDC_NAME_LBL                    1158
#define IDC_NAME_LBL2                   1160
#define IDC_INST_LIST                   1162
#define IDC_INCL_NOTELIST               1163
#define IDC_INCL_SEQUENCE               1164
#define IDC_INCL_SCRIPTS                1165
#define IDC_INCL_TEXTFILES              1166
#define IDC_DEF_PROJECTS                1167
#define IDC_DEF_AUTHOR                  1168
#define IDC_DEF_WAVEIN                  1169
#define IDC_DEF_FORMS                   1170
#define IDC_LATENCY                     1171
#define IDC_BROWSE_PROJECTS             1172
#define IDC_BROWSE_WAVEIN               1173
#define IDC_WV_TYPE                     1173
#define IDC_WV_PHSLBL                   1174
#define IDC_BROWSE_FORMS                1174
#define IDC_DEF_COPYRIGHT               1175
#define IDC_DEF_LIBRARIES               1176
#define IDC_WVF_ID                      1177
#define IDC_BROWSE_LIBRARIES            1177
#define IDC_INCL_LIBRARIES              1178
#define IDC_DEF_COLORS                  1179
#define IDC_SELTEXT                     1180
#define IDC_BROWSE_COLORS               1180
#define IDC_ALLTEXT                     1181
#define IDC_ITEM_NAME                   1184
#define IDC_ITEM_DESCR                  1185
#define IDC_GENERATE                    1187
#define IDC_SPEAKER                     1188
#define IDC_DISK                        1189
#define IDC_USE_SHARPS                  1190
#define IDC_USE_FLATS                   1191
#define IDC_KBD_LEFT                    1195
#define IDC_KBD_RIGHT                   1196
#define IDC_RENUMBER                    1199
#define IDC_ERROR_LIST                  1200
#define IDC_ERROR_ITEMS                 1201
#define IDC_ERROR_GOTO                  1202
#define IDC_ERROR_NEXT                  1203
#define IDC_ERROR_PREV                  1204
#define IDC_MS_TYPE                     1205
#define IDC_MS_UGENS                    1206
#define IDC_MS_ADD                      1207
#define IDC_MS_REM                      1208
#define IDC_MS_MVUP                     1209
#define IDC_MS_MVDN                     1210
#define IDC_MS_NAME                     1211
#define IDC_MC_SRC                      1212
#define IDC_MC_DST                      1213
#define IDC_MC_PARAM                    1214
#define IDC_MC_CONN                     1215
#define IDC_MC_ADD                      1216
#define IDC_MC_REM                      1217
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_VIEW_PROJECT                 32775
#define ID_VIEW_PLAYER                  32776
#define ID_VIEW_MIXER                   32777
#define ID_EDIT_PROPERTIES              32788
#define ID_EDIT_SELECTALL               32789
#define ID_EDIT_FINDREPLACE             32791
#define ID_PROJECT_GENERATE             32798
#define ID_PROJECT_PROPERTIES           32816
#define ID_PROJECT_PLAY                 32826
#define ID_NEW_PROJECT                  32829
#define ID_NEW_NOTELIST                 32830
#define ID_GEN_SOUND                    32854
#define ID_GEN_CD                       32855
#define ID_EDIT_FINDNEXT                32856
#define ID_EDIT_GOTOLINE                32857
#define ID_VIEW_KEYBOARD                32878
#define ID_PROJECT_OPTIONS              32899
#define ID_WINDOW_SAVE                  32905
#define ID_TABMENU_CLOSE                32913
#define ID_PROJECT_SAVE                 32923
#define ID_PROJECT_OPEN                 32924
#define ID_PROJECT_NEW                  32925
#define ID_ITEM_SAVE                    32926
#define ID_ITEM_SAVEAS                  32927
#define ID_ITEM_CLOSE                   32928
#define ID_ITEM_NEW                     32929
#define ID_ITEM_ADD                     32930
#define ID_ITEM_PROPERTIES              32931
#define ID_ITEM_EDIT                    32933
#define ID_ITEM_REMOVE                  32934
#define ID_PROJECT_SAVEAS               32937
#define ID_ITEM_COPY                    32938
#define ID_PROJECTITEMS_NEW             32944
#define ID_PROJECTITEMS_COPY            32945
#define ID_SYNTH_NEWWAVETABLE           32946
#define ID_SYNTH_PROPERTIES             32947
#define ID_WAVEOUT_PROPERTIES           32948
#define ID_FILELIST_NEWFILE             32949
#define ID_FILELIST_ADDEXISTINGFILE     32950
#define ID_Menu32951                    32951
#define ID_RECENTPROJECTS_FILE5         32952
#define ID_RECENTPROJECTS_FILE6         32953
#define ID_EDIT_PROPERTIES32954         32954
#define ID_EDIT_INFO                    32955
#define ID_ITEM_INFO                    32956
#define ID_PROJECTITEMS_INFO            32957
#define ID_ITEM_ERRORS                  32958
#define ID_VIEW_SCOREERRORS             32959
#define ID_HELP_CONTENTS                32968
#define ID_MARKER_SET                   32969
#define ID_MARKER_NEXT                  32970
#define ID_EDIT_SETMARKER               32973
#define ID_EDIT_NEXTMARKER              32974
#define ID_MARKER_PREV                  32975
#define ID_EDIT_PREVIOUSMARKER          32976
#define ID_EDIT_REMOVEALLMARKERS        32977
#define ID_MARKER_CLEAR                 32979

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        353
#define _APS_NEXT_COMMAND_VALUE         32980
#define _APS_NEXT_CONTROL_VALUE         1218
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
